title: "The Burning Horizon"
description: "heat.perception.body.world"
url: "https://gideonmathson.github.io"
baseurl: "/The-Burning-Horizon"
markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: Asia/Kolkata
future: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
